In [1]:
import pandas as pd

In [4]:
library = pd.read_csv("../data/visit2_seq_lib.csv")
library["ProteinSeq"] = library["ProteinSeq"].astype(str).str.strip().str.upper()
library = library[["ProteinSeq"]].drop_duplicates()
library

                                     ProteinSeq
0      STIPLDFMPRDALHGFDWSEEDDMSDGLPFLKTDPNNNGF
1      STIPLDAMPRDALHGADASEEDDMSDGLPALKTDPNNNGA
2      STIPADFMPRDAAHGFDWSEEDDMSDGAPFAKTDPNNNGF
3      STDSTPMFEYENLEDNSKEWTSLFDNDIPVTTDDVSLADK
4      STDSTPMFEYENLEDNSKEATSAADNDIPVTTDDVSLADK
...                                         ...
23342  EDPTWFDDDEQFIDDEQQLVEALSLCDDLDDEQDREENTN
23343  QFIDDEQQLVEALSLCDDLDDEQDREENTNSGSLKDKQPC
23346  IADYAHLGPEDFKRDLEECQKIVLDPSNDEDDEPPEDRDE
23347  DFKRDLEECQKIVLDPSNDEDDEPPEFRDEQDEFDEQDDF
23348  QKIVLDPSNDEDDEPPEFRDEQDEFDEQDDFLAWGTGKTD

[19513 rows x 1 columns]

In [7]:
ec_activities = pd.read_csv("../data/Sog1_library2_activities_with_reads_ECspike.csv")
ec_activities["AAseq"] = ec_activities["AAseq"].astype(str).str.strip().str.upper()
ec_activities = ec_activities[["AAseq"]].drop_duplicates()
ec_activities

                                          AAseq
0      KQRQNQNQGQQQPTWFQSGSQFILNSQQLVQALSLCQQLL
1      KQRDNEDNGEEDPTWFDSGSQFILNSQQLVEALSLCDDLL
2      KQRSIPLSPIVPESSDPAALKRARNTEAARRSRARKLQRM
3      KQIDIYKYDPWDLPRVSSVGEKEWYFFCMRGRKYRNSVRP
4      KQIVLDPSNIELDTPPEFRLSQLEFGSQDSFLAWGTGKTD
...                                         ...
11264  FDSPDVAESFETSPLFANADADLAGQDAWFSLFPSISGGE
11265  FDWEPTDSGSQFILNSQQLVEALSLCDDLLGSQDREENTN
11266  FAAGARKRRKIHDDDFGDVRWHKAGRAKPVVLDGVQRGCK
11267  FVKDSLQDIGKYFEIDSTLDELEQVESGEGNDDLPDEEER
11268  FVASQLMSQEDGVSGFGGHHEEDNNKIGHYNNEESNNKGS

[11269 rows x 1 columns]

In [8]:
ec_activities[ec_activities["AAseq"].isin(library["ProteinSeq"])]

                                          AAseq
0      KQRQNQNQGQQQPTWFQSGSQFILNSQQLVQALSLCQQLL
1      KQRDNEDNGEEDPTWFDSGSQFILNSQQLVEALSLCDDLL
2      KQRSIPLSPIVPESSDPAALKRARNTEAARRSRARKLQRM
3      KQIDIYKYDPWDLPRVSSVGEKEWYFFCMRGRKYRNSVRP
4      KQIVLDPSNIELDTPPEFRLSQLEFGSQDSFLAWGTGKTD
...                                         ...
11264  FDSPDVAESFETSPLFANADADLAGQDAWFSLFPSISGGE
11265  FDWEPTDSGSQFILNSQQLVEALSLCDDLLGSQDREENTN
11266  FAAGARKRRKIHDDDFGDVRWHKAGRAKPVVLDGVQRGCK
11267  FVKDSLQDIGKYFEIDSTLDELEQVESGEGNDDLPDEEER
11268  FVASQLMSQEDGVSGFGGHHEEDNNKIGHYNNEESNNKGS

[11019 rows x 1 columns]

In [9]:
19513-11019

8494

In [10]:
11269-11019

250